import "@/styles/globals.css";
import Header from "./_components/Header";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Footer } from "./_components/Footer";
import { ToastProvider } from "@/components/ui/toast";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex min-h-screen flex-col">
        <Header />
        <main className="flex-grow container mx-auto max-w-6xl px-6 pt-6 pb-8">
          {children}
        </main>
        <ToastProvider>
          <Footer />
        </ToastProvider>
      </body>
    </html>
  );
}
